<a href="https://colab.research.google.com/github/schizohub/PyTorch_lessons/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch fundamentals**

In [1]:
!nvidia-smi

Sun Jan 22 11:20:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P0    31W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
import numpy as np
import pandas as pd

print(torch.__version__)

1.13.1+cu116


### Intro to tensors(types of tensors)

In [3]:
#scalar tensor

scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
 #vector tensor

 vector = torch.tensor([4,4])
 vector

tensor([4, 4])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix tensor

matrix = torch.tensor([[7,8],
                       [9,8]])
matrix

tensor([[7, 8],
        [9, 8]])

In [10]:
 matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
#Tensor main

Tensor = torch.tensor([[[9,9,9],
                        [0,0,0],
                        [8,8,8]]])
Tensor

tensor([[[9, 9, 9],
         [0, 0, 0],
         [8, 8, 8]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [16]:
Tensor[0]

tensor([[9, 9, 9],
        [0, 0, 0],
        [8, 8, 8]])

#Random tensors 

In [17]:
#Random tensor  
random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.4004, 0.5551, 0.3324, 0.6424],
        [0.7212, 0.4087, 0.2816, 0.6551],
        [0.0481, 0.9853, 0.8149, 0.1624]])

In [18]:
random_tensor.ndim

2

In [19]:
#Random tensor with shape to an image tensor

random_size_image_tensor = torch.rand(size=(224,224,3)) #height, width, color channel(R,G,B)
random_size_image_tensor.shape, random_size_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
random_size_image_tensor[0][:5]

tensor([[0.0347, 0.9232, 0.6488],
        [0.2563, 0.0397, 0.4531],
        [0.3481, 0.4012, 0.0889],
        [0.4459, 0.7873, 0.0712],
        [0.1510, 0.9614, 0.2071]])

# Ones and zeros tensors

In [21]:
#Zeros tensor

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Ones zeros

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
 ones*34

tensor([[34., 34., 34., 34.],
        [34., 34., 34., 34.],
        [34., 34., 34., 34.]])

In [25]:
ones.dtype

torch.float32

# Tensors with range

In [26]:
#Torch.range()

torch.range(0,10)

<ipython-input-26-87538370959b>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
#torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
ten_zeros = torch.zeros_like(input=one_to_ten)

In [30]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
torch.zeros_like(input=torch.tensor([1,3,2,4,6]))

tensor([0, 0, 0, 0, 0])

# Data Types

In [32]:
float_32_tensor = torch.tensor([9.0,8.0,2.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.half)

In [34]:
float_16_tensor

tensor([9., 8., 2.], dtype=torch.float16)

In [35]:
mult = float_16_tensor*float_32_tensor

In [36]:
mult.dtype

torch.float32

In [37]:
integer_32 = torch.tensor([9,2,3],dtype=torch.int32)
integer_32

tensor([9, 2, 3], dtype=torch.int32)

In [38]:
integer_32*float_16_tensor

tensor([81., 16.,  6.], dtype=torch.float16)

# Getting info from tensor

In [39]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7194, 0.7887, 0.4159, 0.8049],
        [0.0451, 0.5616, 0.1876, 0.6421],
        [0.6528, 0.8040, 0.3948, 0.3097]])

In [40]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device}")

tensor([[0.7194, 0.7887, 0.4159, 0.8049],
        [0.0451, 0.5616, 0.1876, 0.6421],
        [0.6528, 0.8040, 0.3948, 0.3097]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


# Tensor manipulating

In [41]:
#Addition
tensor = torch.tensor([1,2,3])
tensor+10
tensor+100

tensor([101, 102, 103])

In [42]:
#Multiplacation
tensor*10

tensor([10, 20, 30])

In [43]:
#Subtraction
tensor - 3

tensor([-2, -1,  0])

In [44]:
#PyTorch function for arithmetic
torch.mul(tensor,10)


tensor([10, 20, 30])

In [45]:
torch.div(tensor,2)

tensor([0.5000, 1.0000, 1.5000])

In [46]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [47]:
torch.add(tensor,11)

tensor([12, 13, 14])

# Matrix multiplication


In [48]:
#Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals : {tensor**2}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [49]:
#Matrix multiplication(part1)
%%time
torch.matmul(tensor,tensor)

CPU times: user 4.49 ms, sys: 0 ns, total: 4.49 ms
Wall time: 4.62 ms


tensor(14)

In [50]:
%%time
s = 0
for i in tensor:
    s+=i*i
print(s)

tensor(14)
CPU times: user 3.64 ms, sys: 64 µs, total: 3.7 ms
Wall time: 3.4 ms


In [51]:
%%time 
s = 0
for i in range(len(tensor)):
    s+= tensor[i]*tensor[i]
print(s)


tensor(14)
CPU times: user 237 µs, sys: 44 µs, total: 281 µs
Wall time: 288 µs


In [52]:
tens = torch.rand(3,4)
tens

tensor([[0.0193, 0.7332, 0.3841, 0.9225],
        [0.1694, 0.0998, 0.9761, 0.0107],
        [0.5592, 0.3124, 0.9442, 0.9087]])

In [53]:
tens.T

tensor([[0.0193, 0.1694, 0.5592],
        [0.7332, 0.0998, 0.3124],
        [0.3841, 0.9761, 0.9442],
        [0.9225, 0.0107, 0.9087]])

In [54]:
#Matrix multiplication (part 2)

TENSOR_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

TENSOR_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]]) 

In [55]:
TENSOR_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [56]:
torch.mm(TENSOR_A,TENSOR_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [57]:
torch.matmul(TENSOR_A,TENSOR_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Tensor aggregation(max,min,sum, etc.)

In [58]:
#Finding max,min,mean and sum etc. of tensors

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
# min() function

torch.min(x), x.min()

(tensor(0), tensor(0))

In [60]:
# max() function

torch.max(x), x.max()

(tensor(90), tensor(90))

In [61]:
# average for tensor --> mean() requires a float or complex dtype 

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
# sum function

torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [63]:
#Positional min()- returns an index of tensor

x.argmin()

tensor(0)

In [64]:
#Positional max() - returns an index of tensor

x.argmax()

tensor(9)

# Reshaping, stacking, squeezing and unsqueezing tensor
* Reshaping - reshapes an input tensor to a defined shape
* View - returns a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing - removes all 1-ds from a tensor
* Unsqueezing - add 1-d to a target tensor
* Permute - return a view of the input with dimensions permuted(swapped) in a certain way 

In [65]:
# Tensor

x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [66]:
#Reshaping - reshapes an input tensor to a defined shape

x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]), torch.Size([9, 1]))

In [67]:
#Change the view

z = x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [68]:
#Changing z changes x (cause the view of a tensor shares the same memory as the original tensor)

z[:, 0] =5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [69]:
#Stack tensors on top of each other with stack() function. It belongs to dimension of a given tensor

x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [70]:
# Squeeze. torch.squeeze() --> removes all single dimensions from a target tensor

y = torch.squeeze(x_stacked,dim=0)
y.size()

torch.Size([9, 4])

In [71]:
y[[0]].squeeze().shape

torch.Size([4])

In [72]:
y[[0]].shape

torch.Size([1, 4])

In [73]:
#Unsqueeze. torch.unsqueeze() --> adds a single dimension to a target tensor at a specific dim
x_unsqueezed = x.unsqueeze(dim=1)
x_unsqueezed

tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [74]:
#torch.permute() --> rearranges the dimensions of a tensor
x1 = torch.randn(2,3,5)
x1.size()

torch.Size([2, 3, 5])

In [75]:
x1.permute(2,0,1) # shifts axis 0->1, 1->2, 2->

tensor([[[ 0.1167,  1.7224, -1.5638],
         [ 0.6312,  0.4748,  0.6370]],

        [[-0.7599, -0.0692, -1.5949],
         [ 2.0104,  0.2097, -1.0967]],

        [[ 0.8263, -1.4902,  0.9550],
         [-0.3461,  0.3357,  0.0391]],

        [[-1.4955,  0.7086,  1.4939],
         [ 0.2132, -0.6835,  1.4874]],

        [[ 2.2114, -0.4940,  1.8743],
         [ 0.2511,  0.8923,  0.1384]]])

In [76]:
x1

tensor([[[ 0.1167, -0.7599,  0.8263, -1.4955,  2.2114],
         [ 1.7224, -0.0692, -1.4902,  0.7086, -0.4940],
         [-1.5638, -1.5949,  0.9550,  1.4939,  1.8743]],

        [[ 0.6312,  2.0104, -0.3461,  0.2132,  0.2511],
         [ 0.4748,  0.2097,  0.3357, -0.6835,  0.8923],
         [ 0.6370, -1.0967,  0.0391,  1.4874,  0.1384]]])

In [77]:
print(f"Previous shape: {x1.shape}")
print(f"Previous tensor: \n{x1} \n")
print(f"New shape: {x1.permute(2,0,1).shape}")
print(f"New tensor: \n{x1.permute(2,0,1)}")

Previous shape: torch.Size([2, 3, 5])
Previous tensor: 
tensor([[[ 0.1167, -0.7599,  0.8263, -1.4955,  2.2114],
         [ 1.7224, -0.0692, -1.4902,  0.7086, -0.4940],
         [-1.5638, -1.5949,  0.9550,  1.4939,  1.8743]],

        [[ 0.6312,  2.0104, -0.3461,  0.2132,  0.2511],
         [ 0.4748,  0.2097,  0.3357, -0.6835,  0.8923],
         [ 0.6370, -1.0967,  0.0391,  1.4874,  0.1384]]]) 

New shape: torch.Size([5, 2, 3])
New tensor: 
tensor([[[ 0.1167,  1.7224, -1.5638],
         [ 0.6312,  0.4748,  0.6370]],

        [[-0.7599, -0.0692, -1.5949],
         [ 2.0104,  0.2097, -1.0967]],

        [[ 0.8263, -1.4902,  0.9550],
         [-0.3461,  0.3357,  0.0391]],

        [[-1.4955,  0.7086,  1.4939],
         [ 0.2132, -0.6835,  1.4874]],

        [[ 2.2114, -0.4940,  1.8743],
         [ 0.2511,  0.8923,  0.1384]]])


# Indexing (selecting data from tensors)
Indexing with PyTorch is similiar to indecing NumPy: 
* NumPy --> arrays:
`np.array([data])[0:2]`
* PyTorch --> tensors:
`torch.tensor([data])[0:2]`

In [78]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [79]:
x.shape

torch.Size([1, 3, 3])

In [80]:
x.ndim

3

In [81]:
#Indexing

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [82]:
x[0][0]

tensor([1, 2, 3])

In [83]:
x[0][0][0]

tensor(1)

In [84]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [85]:
# to get 9
x[-1][-1][-1]

tensor(9)

In [86]:
x.ndim

3

In [87]:
# to get 3,6,9 
x[:,:,2]

tensor([[3, 6, 9]])

In [88]:
y = x

In [89]:
x = torch.tensor([[1,2,3],
       [4,5,6],
       [9,8,9]])

In [90]:
y.ndim==x.ndim

False

In [91]:
[x[i][len(x)-1-i] for i in range(len(x))]

[tensor(3), tensor(5), tensor(9)]

In [92]:
[x[i][i] for i in range(len(x))]

[tensor(1), tensor(5), tensor(9)]

# PyTorch and NumPy

In [93]:
arr = np.array([[1,2,3],
       [4,5,6],
       [9,8,9]])

In [94]:
f = torch.from_numpy(arr)

In [95]:
f.ndim==arr.ndim

True

In [96]:
arr1 = torch.Tensor.numpy(f)

In [97]:
arr==arr1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [98]:
arr,f

(array([[1, 2, 3],
        [4, 5, 6],
        [9, 8, 9]]), tensor([[1, 2, 3],
         [4, 5, 6],
         [9, 8, 9]]))

In [99]:
print(type(arr))
print(type(f))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [100]:
#numpy to pytorch -> array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch, pytoch reflects numpy's default dtype of float64 unless specified type 
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [101]:
array, tensor.type(torch.float32)

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [102]:
#change the value of array, what will this do to tensor

array+=1 #if array is changed, but tensor won't be changed 
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [103]:
#tensor to numpy

tensor = torch.ones(8)
numpy_from_tensor = tensor.numpy()

tensor, numpy_from_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [104]:
#change the tensor, what happens to numpy

tensor+=1# if tensor is changed, but array won't be changed

tensor, numpy_from_tensor


(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducability(trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of tha data again -> again -> again ->...`
To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness


In [105]:
torch.rand(3,3)

tensor([[0.2090, 0.2771, 0.6475],
        [0.4944, 0.5221, 0.7936],
        [0.8277, 0.9258, 0.9940]])

In [106]:
# Create 2 random tensor

random_A = torch.rand(3,4)
random_B = torch.rand(3,4)

print(random_A)
print(random_B)
print(random_A==random_B)

tensor([[0.0152, 0.3757, 0.2531, 0.1509],
        [0.0716, 0.1165, 0.0827, 0.2206],
        [0.6853, 0.2851, 0.2710, 0.1992]])
tensor([[0.3751, 0.0259, 0.0814, 0.5633],
        [0.0653, 0.4460, 0.9882, 0.6978],
        [0.0697, 0.4091, 0.5584, 0.3433]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [107]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running tensors and PyTorch objects with accessing the GPUs to make faster computations.

In [108]:
torch.cuda.is_available()

True

In [109]:
!nvidia-smi

Sun Jan 22 11:20:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0    31W /  70W |      3MiB / 15109MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##Putting models and tensors on the GPU

In [110]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [111]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor_on_gpu = tensor.to(device)

In [112]:
print(tensor_on_gpu)

tensor([1, 2, 3], device='cuda:0')
